### PR TITLE
Restore Fresh 2 compatibility in Fedify

### LINKED ISSUE #621: Error when trying to load Fedify 2.0 from a Fresh 2.0 app
### Summary

I am attempting to upgrade my Fedify application from Fedify 1.x and Fresh 1.x to version 2.0 of both frameworks. I am running into fatal errors seemingly related to the multicodec module that prevent the pages from rendering as soon as I invoke Fedify.

Note that this is not about the middleware integration, which I have not yet attempted. This is just about running Fresh 2.0 and Fedify 2.0 within the same codebase.

This bug report comes with a big caveat: I have not yet tested Fedify 2.0 *without* Fresh 2.0, and as a result I am not sure if Fresh 2.0 is indeed a necessary component to trigger this error. My assumption is that there must be something about my project environment that triggers it for me but not others, and Fresh 2.0 seems like the most obvious candidate.

### Expected Behavior

Fedify 2.0 should not prevent Fresh 2.0 apps from functioning.

### Actual Behavior

Running Fedify 2.0 in a Fresh 2.0 application causes a fatal error.

### Environment

- Deno 2.7.5
- Fedify 2.0.5
- Fresh 2.2.0 (using vite 7.3.1)

Running on Linux

### Logs / Screenshots

```
GET http://localhost:5174/
TypeError: varint.encode is not a function
    at varintEncode (./node_modules/.deno/multicodec@3.2.1/node_modules/multicodec/src/util.js:40:1)
    at ./node_modules/.deno/multicodec@3.2.1/node_modules/multicodec/src/maps.js:20:29
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (./node_modules/.deno/multicodec@3.2.1/node_modules/multicodec/src/index.js:15:1)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/vocab-runtime/2.0.5/src/key.ts:13:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/vocab-runtime/2.0.5/src/mod.ts:27:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/webfinger/2.0.5/src/lookup.ts:4:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/webfinger/2.0.5/src/mod.ts:5:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/vocab/2.0.5/src/actor.ts:8:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/vocab/2.0.5/src/mod.ts:4:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/fedify/2.0.5/src/federation/builder.ts:5:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
    at async SSRCompatModuleRunner.cachedRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1053:73)
    at async eval (deno::0::https://jsr.io/@fedify/fedify/2.0.5/src/federation/mod.ts:9:31)
    at async ESModulesEvaluator.runInlinedModule (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:913:3)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/module-runner.js:1146:59)
    at async SSRCompatModuleRunner.directRequest (./node_modules/.deno/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:15111:22)
error: Uncaught NotFound: No such file or directory (os error 2) about ["./routes/.goutputstream-RZE2L3"]
    at new FsWatcher (ext:runtime/40_fs_events.js:23:17)
    at Object.watchFs (ext:runtime/40_fs_events.js:73:10)
    at ext:deno_node/_fs/_fs_watch.ts:57:21
    at callback (ext:deno_web/02_timers.js:42:7)
```

Note: I have replaced my full project path with "`.`" in the above logs.

### Steps to Reproduce

1. Create a Fresh 2.0 demo project: `deno run -Ar jsr:@fresh/init`
2. Navigate into the project directory and add Fedify: `deno add jsr:@fedify/fedify`
3. Edit `routes/index.tsx`:
    1.  Add `import { createFederation } from "@fedify/fedify";` near the top of the file
    2. Somewhere within `Home`, for example after the console output, add `createFederation<null>();`
4. Run `deno task dev`
5. Open the website in the browser and observe the error messages

### PR DESCRIPTION
**Pull request by dahlia**
Summary
-------

This PR restores Fresh 2 compatibility in Fedify by removing two SSR-hostile dependency paths and by validating the Fresh example end-to-end on Deno 2.7.7.

Closes #621.

Changes
-------

 -  Replaced the `multicodec` dependency in *packages/vocab-runtime/src/key.ts* with an internal multicodec/varint helper implemented in *packages/vocab-runtime/src/internal/multicodec.ts*.
 -  Added regression tests for the new helper in *packages/vocab-runtime/src/internal/multicodec.test.ts* and extended malformed-input coverage in *packages/vocab-runtime/src/key.test.ts*.
 -  Removed the `multicodec` dependency from the relevant manifests, including *packages/vocab-runtime/deno.json* and *packages/vocab-runtime/package.json*.
 -  Added the new `@fedify/vocab-runtime/jsonld` subpath export in *packages/vocab-runtime/src/jsonld.ts* so Fedify and generated vocabulary code can share one JSR-safe wrapper around the `jsonld` ESM entrypoint.
 -  Updated *packages/fedify/src/sig/ld.ts* and the code generated through *packages/vocab-tools/src/class.ts* to import JSON-LD support through `@fedify/vocab-runtime/jsonld` instead of depending on fragile relative shims or the package-root `jsonld` entrypoint.
 -  Updated the generated-code snapshots in *packages/vocab-tools/src/class.test.ts* and *packages/vocab-tools/src/__snapshots__/* so Deno, Node.js, and Bun all expect the same runtime import path.
 -  Removed the Fresh-specific SSR externalization workaround from *examples/fresh/vite.config.ts*.
 -  Extended the Fresh example in *examples/fresh/federation.ts* so it exercises an actual actor JSON-LD response path instead of only the landing page and NodeInfo endpoints.
 -  Updated the Fresh integration guidance in *docs/manual/integration.md*, the example notes in *examples/fresh/README.md*, and the changelog in *CHANGES.md*.
 -  Bumped the verified Deno version for Fresh development to 2.7.7 in *mise.toml* and *.github/actions/setup-deno/action.yaml*.

Investigation
-------------

This issue turned out to have multiple layers rather than a single Fresh-specific bug.

The first failure reproduced in Fresh 2 SSR was `TypeError: varint.encode is not a function`. Tracing the import graph showed that the failure came from the multibase key path in *packages/vocab-runtime/src/key.ts*, which depended on `multicodec`. That package was safe enough in other environments but became fragile when evaluated through Fresh 2's SSR toolchain. Since Fedify only needs a very small subset of multicodec behavior there, the most robust fix was to stop depending on the package at runtime and replace it with a local helper that only handles the supported prefixes and varint encoding and decoding logic.

After that change, the original error disappeared, but Fresh still failed in a different place with `buildHeaders is not a function`. That pointed to a second SSR-hostile path: the default `jsonld` entrypoint. The important detail here was that Fresh users typically consume Fedify through JSR, so fixing only npm build artifacts under *dist/* would not have solved the actual problem. The real fix had to happen in the source modules that are published to JSR, which is why this PR changes the imports in *packages/fedify/src/sig/ld.ts* and in the generated vocabulary source path produced by *packages/vocab-tools/src/class.ts*.

The first version of that fix switched those imports directly to `jsonld/dist/jsonld.esm.js`, which solved the runtime issue but still left two structural problems. First, generated code had to rely on a package-local shim file through a relative import, which was more fragile than necessary. Second, a `declare module` approach for typing that deep import turned out to be incompatible with JSR publishing because JSR rejects packages that modify global types. The final shape in this PR is therefore a dedicated `@fedify/vocab-runtime/jsonld` subpath export. It centralizes the deep import in one runtime package that generated vocab code is already meant to depend on, avoids relative-path coupling in generated sources, and remains valid for both JSR and npm packaging.

Once those two Fedify-side issues were fixed, Fresh dev mode still crashed, but the error had changed again to `The service is no longer running: Callback called multiple times` while evaluating `fresh/build-id` through Vite. At that point the failure no longer implicated Fedify directly. Verifying against Deno release information and rerunning the example on Deno 2.7.7 showed that this remaining crash was an upstream Deno regression in 2.7.6 rather than another Fedify bug. In other words, the Fedify fixes in this PR remove the SSR incompatibilities that belonged to Fedify itself, and the final end-to-end verification succeeds once the underlying Deno regression is no longer present.

One smaller follow-up that surfaced during verification was that `mise run test:bun` still failed even after the functional fixes were complete. That was not a runtime regression but a stale snapshot in *packages/vocab-tools/src/__snapshots__/class.test.ts.snap*, which still expected the older import path after the generator had been updated. Refreshing the Bun, Node.js, and Deno snapshots brought all three runtimes back in line.

Benefits
--------

These changes remove the need for the previous Fresh SSR workaround, make the fix apply to both the JSR and npm package paths instead of only one packaging format, and keep the affected code paths portable across Deno, Node.js, Bun, and Cloudflare Workers.

Verification
------------

 -  Ran the new and updated regression tests for the multicodec helper and key import path.
 -  Ran the affected Fedify and vocabulary JSON-LD tests after switching to the shared `@fedify/vocab-runtime/jsonld` runtime path.
 -  Refreshed and rechecked the Deno, Node.js, and Bun snapshots for generated vocabulary imports.
 -  Confirmed that the Fresh example works on Deno 2.7.7 with `deno task dev` and `deno task build`.
 -  Verified the Fresh example endpoints `/`, `/nodeinfo/2.1`, and `/users/sample` with `Accept: application/activity+json`.
 -  Confirmed that the earlier Fresh errors `varint.encode is not a function` and `buildHeaders is not a function` no longer reproduce.
 -  Confirmed that `deno publish --dry-run --allow-dirty` succeeds in both *packages/vocab-runtime/* and *packages/vocab/*.
 -  Confirmed that `mise run test:bun` passes after refreshing the runtime-specific snapshots.

Checklist
---------

 -  [x] Did you add a changelog entry to the *CHANGES.md*?
 -  [x] Did you write some relevant docs about this change (if it's a new feature)?
 -  [x] Did you write a regression test to reproduce the bug (if it's a bug fix)?
 -  [ ] Did you write some tests for this change (if it's a new feature)?
 -  [ ] Did you run `mise test` on your machine?

Additional notes
----------------

 -  The final Fresh verification result depends on Deno 2.7.7 or later because Deno 2.7.6 still had an upstream dev-mode regression unrelated to Fedify itself.
 -  AI-assisted: this PR was updated with help from Codex.

### CODE REVIEW

File: packages/fedify/src/sig/ld.ts [hunk 1]
```diff
@@ -4,7 +4,8 @@ import { getLogger } from "@logtape/logtape";
 import { SpanStatusCode, trace, type TracerProvider } from "@opentelemetry/api";
 import { decodeBase64, encodeBase64 } from "byte-encodings/base64";
 import { encodeHex } from "byte-encodings/hex";
-import jsonld from "jsonld";
+// @ts-ignore TS7016
+import jsonld from "jsonld/dist/jsonld.esm.js";
```
[the remark this answers is not in the document]
Comment (dahlia) [reply packages/fedify/src/sig/ld.ts]: Applied in 38c90404.

I replaced the local `@ts-ignore` with a declaration for `jsonld/dist/jsonld.esm.js` in *packages/vocab/src/jsonld-esm.d.ts*, then updated the generator in *packages/vocab-tools/src/class.ts* so the generated source and snapshots use the same typed import path.

I also re-ran the affected checks and tests after the change.
